### ISSUE TITLE
Stuck in boot with KP (Resolved - issue was with AppleIntelE1000e.kext)

### ISSUE THREAD

**Issue by FelipousisMix** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#1]
Hi: I have changed my CPUs to 2650V2 to match one of your SSDTs, the config.plist passes fine, no complaints from the validators, however, I always got some ERR (0xE) errors. How can I review this?

HP Z820 currently running Mojave with Clover, no issues at all.

Bios J63, V03.96, storage set to AHCI, Secure Boot Disable, VT-d disabled, Legacy ACPI tables enabled
Dual E5 2650 V2 @ 2.6 GHz
32 GB Ram ECC @ 1866 MHz

I tried with the OC 0.7.8 version and same result.

Your guidance will be greatly appreciated it.

[EFI-Logs.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8400947/EFI-Logs.zip)

**Comment by BillDH2k** [comment]
Are you trying to install Big Sur? Monterey? Fresh install or upgrade from existing Mojive? Please be more specific. My EFI 078 is only tested for fresh install of Big Sur/Monterey or upgrade from Big Sur to Monterey.

**Comment by BillDH2k** [comment]
I see that you were trying to install Catalina. Make sure to use my OC071 EFI release (1.0). I cleaned your config.plist you sent to me (removed a couple of SMC sensor related kext). Try it to see if it made any difference.  Note: Since all msg posted here are public, so for safety reason, make sure you change the serial # once your system is up running! 
[config.plist.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8412392/config.plist.zip)

**Comment by FelipousisMix** [comment]
Hi: yes, that’s the one I used but it fails there, for a fresh install of Catalina.

Sent from Mobile, please excuse any typo.
________________________________

**Comment by BillDH2k** [comment]
Just tested your uploaded EFI, without a single change, and boot up Catalina 11.5.7 install USB successfully. My system is Z820 running 2x 2670 V1 CPUs (boot up fine even with 2650V2 CPUPM). So the issue must be your Z820 setup. Make sure the USB install stick is plugged in USB2 port only (the black colored port). You did not state what kind of add-on hardwares you have (video card, etc). Also check your BIOS setup. Visit bilbo's Z820 Guide (see README in the main page), and follow the BIOS recommendation there.

**Comment by BillDH2k** [comment]
One recommendation to your config.plist. For install/debug purpose, change: Misc->Boot->PickerMode->Builtin (so you could see exactly which partition is booted/installed to), and, Misc->Boot->Timeout-> 10 (increase the picker selection time to 10 seconds, you could have time to react for manual selection).

**Comment by FelipousisMix** [comment]
Thanks for your input, I found one kext, the INtel E1000 was causing the KP, now Catalina is up and running.

Thanks a lot for doing this package.

**Comment by BillDH2k** [comment]
Interesting finding? Do you have another ethernet card installed?

IntelE1000.kext is used for dual LAN supports (Z620/Z820). IntelMausi.kext is more stable driver but only support one port.

**Comment by FelipousisMix** [comment]
Sorry for my late reply, yes I have an Intel Pro 1000 also installed.

Thanks for your help!
