### ISSUE TITLE
Z420 e5-1650 v1 Don't seem to be able to boot into opencore

### ISSUE THREAD

**Issue by CBAP72** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#11]
Hi,
I keep getting a blank screen when trying to boot off the usb.
No issues when I put it into my dell and boot of the efi on the usb.  
GC is RX 470 so that should be native?

48 gb of ram.

Have loaded default bios and followed the instruction regarding bios.

Any ideas would be appreciated.

Carl

**Comment by BillDH2k** [comment]
The screen could be directed to another output port. Try to probe other port to check for signal.  Or, If your RX 470 has an UIFI bios, you should turn off the Legacy boot option under Z420 BIOS: Boot Order ->Legacy Boot Source-> Disabled. Then, Security -> Security Boot Configuration -> Legacy Support -> Disabled. By doing these, the video output will stay at the active port, also the screen resolution will be automatically detected.

Warning: if your video card's BIOS is not UEFI capable, turn off the Legacy Boot support in Z420 will prevent you from booting (you will hear 6-beeping error). The only way to recover from this is a bios reset or boot from another video card.

**Comment by BillDH2k** [comment]
If just downloaded zipped release yesterday/today, please re-download it again. I had placed a corrupted USBInjectAll.kext in there by mistake, which will cause problem in booting. I corrected the problem today.
