### ISSUE TITLE
CPU E5-2695V2 support Monterey

### ISSUE THREAD

**Issue by RobvKol** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#13]
Dear All,

with the E4-2643V2 got great results with the Z820 thanks to te supplied OC.
swapped to E5-2695-V2 and got kernel panic during boot
replaced the used config_2643V2.plist to create the config.plist with the config_ivyCPUs.plist but still got the kernel panic.
somebody can help me with the right CPU entries for the E5-2695V2?

regards,
rob

**Comment by BillDH2k** [comment]
Create SyReport dump (using SysReport quirk). Post the following two files here: ACPI-1.aml and SSDT-2.aml.

I will help to take a look and figure out a new ssd file.
