### ISSUE TITLE
Bios update (DELL T5810 related)

### ISSUE THREAD

**Issue by pud469** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#14]
I apologize that this isn't the proper way to communicate, but I found no other way to ask for your help.  I have used OreyM EFI to install MacOS on a Dell T5810.  I see that you posted that you were able to update the bios to A33 and get the machine to boot.  I would like to ask that if you can be so kind to share the EFI you used.  OreyM appears to have closed all his issues and (possibly has) remove the attached EFI you used. I was trying to help him to add instructions to disable the MSR lock on the T5810 and avoid using the PMpatch. Anyway, thanks for any help in advance, if not thanks for sharing your other work here.

**Comment by BillDH2k** [comment]
No problem. Here is my EFI with OC084 for DELL T5810 (BIOS A33). Tested for Big Sur. Also tested for Catalina, but you have to switch to HfsPlusLegacy.efi, and set UEFI->APFS->MinDate/MinVersion-> -1. 

This EFI is optimized from OreyM's work, as well as from another GitHub contributor [here](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore). 

If OC failed to boot under A33, one trick I found was to toggle the  BIOS's setting: [Memory Map IO above 4GB]. Then, reboot. 

Goodluck!

[EFI-T5810-OC084.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/9865219/EFI-T5810-OC084.zip)

**Comment by BillDH2k** [comment]
Hi, I have responded to your request on GitHub. Let me know if you need any
further help.

Best regards,

Bill
