### ISSUE TITLE
Z620 E5-2670 stuck on boot with Er 0xE wake failure

### ISSUE THREAD

**Issue by kiraly87** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#15]
Hi,

I'm trying to install MacOS Monterey using your latest EFI. I reseted the bios, set all the settings ("Z820 - High Sierra, the Great Guide"), used config_SandyCPUs.plist, added my Serial # & Board ID, set the SSDT-CPUPM.aml using SSDT-2670.aml but I get the following error:
![20221114_135033](https://user-images.githubusercontent.com/19572560/201656217-8fd3a476-10f3-40ec-94a6-006187f87e2b.jpg)

What I'm doing wrong ?

Thanks!

**Comment by kiraly87** [comment]
Log file:
[opencore-2022-11-14-155629.txt](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/10006268/opencore-2022-11-14-155629.txt)

**Comment by BillDH2k** [comment]
> 00:000 00:000 OC: OpenCore DBG-071-2021-07-05 is loading in Optional mode (0/0)...

Monterey install must use my OC 0.8.4 EFI. From your log, you appeared using 0.7.1. Check README.MD again.

**Comment by kiraly87** [comment]
Oh, with 0.7.1 I tried Catalina, for Monterey I used 0.8.4. Result was the
same, stuck on the same place :(

BillDH2k ***@***.***> ezt írta (időpont: 2022. nov. 14., Hét
23:53):

**Comment by BillDH2k** [comment]
Did you try to Reset NVRAM first (from the OpenCore picker screen) before launching Monterey? Also I've had trouble with Monterey 12.5 (other versions are fine), I suggest try latest Monterey 12.6. 

Also, if you have any add-on cards, may be you should temporarily remove them if you still have trouble booting.  In addition, make sure you use AppleIntelE1000.kext for LAN driver (for Z620).

Your previous log showed you're booting Catalina, not Monterey:
> 98:246 00:024 OCOS: OS set: <null> Mac OS X 10.15
> 98:271 00:024 OCOS: OS set: Apple Inc. Mac OS X 10.15

**Comment by kiraly87** [comment]
Thank you for the reply, I installed Monterey 12.5 (downloaded the full installer not just thre recovery image and worked that way) but seems like my video card (Nvidia Quadro K2200) not supported. I tried the opencore legacy patcher but the screen went pink after the restart :) I'm trying to install Big Sur now, I hope that my video card will work with that. I want to use Final Cut software and that requires 11.5.1 at least.

**Comment by BillDH2k** [comment]
Nvidia Quadro K2200 is based on Maxwell core ([link](https://www.techpowerup.com/gpu-specs/quadro-k2200.c2601)). macOS support stopped at High Sierra. Not sure if OPLP can bring back the hardware acceleration on this card, but it worth try. You best bet is to find an AMD card.
