### ISSUE TITLE
Ventura compatibility

### ISSUE THREAD

**Issue by aferrara814** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#16]
IS not compatible with ventura version?

I am still working on latest montery with you EFI dir, and it's amazing.

If I try to update or do a fresh install I get this 2 errors

![IMG_3794](https://user-images.githubusercontent.com/83160600/204017730-0df194fc-ee65-4c0e-81be-dc8d2d2e9ea8.jpg)
![IMG_3796](https://user-images.githubusercontent.com/83160600/204017739-8f88ebdc-5192-43c9-aedd-34da351de38a.jpg)

**Comment by BillDH2k** [comment]
No Ventura support for Sandy/Ivy-bridge CPUs (no AVX2 instruction set in these CPUs).

**Comment by aferrara814** [comment]
Yes I know, so if I upgrade on E5-26xx V3 or V4 I can execute it on my z620?

Not exist any other solution of this problem?

**Comment by BillDH2k** [comment]
This platform, X79, only supports V1/V2 Xeons, not V3/V4 which needs X99 platform, such as Z440/640/840.

**Comment by aferrara814** [comment]
Thank you so much! There is an OC EFI ready/patched for z4g4?
I'm thinking of buying a new z workstation

**Comment by BillDH2k** [comment]
I don't own Z4G4 hardware, thus won't be able to help.
