### ISSUE TITLE
Z800 compatibility

### ISSUE THREAD

**Issue by sreealeti** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#18]
Hi , i am trying to use this for HP Z800 which is similar to Z820 but it doesnt work for monterey or big sur. Since its very similar trying to check if you can help.
HP Z800
CPU: 2 x X5650 2.67GHz
RAM: 72GB
Graphics:  2 x Quadro FX 570
monitors : 3
BIOS: 3.96

**Comment by BillDH2k** [comment]
Z800 is a very different board and CPU. Thus you can not use the EFI from here. 
But you should check this link [here](https://www.insanelymac.com/forum/topic/351052-for-mac-os-12-monterey-installation-on-hp-z800-workstation-computer-with-efi-for-reference/#comment-2777989), and [here](https://www.insanelymac.com/forum/topic/348177-hp-z800-anyone-working-on-this-with-current-07-opencore-versions/ ).
