### ISSUE TITLE
Did you get a NVMe ssd card working

### ISSUE THREAD

**Issue by adrianboston** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#19]
It seems you did get a NVMe ssd working on your z workstations??

Ive read in HP forums that only a select few ssds -- such as the Samsung 950 Pro -- with nvme bios in the firmware.

BUT, then opencore is a UEFI boot loader so perhaps any card is possible.

Any thoughts here?

**Comment by BillDH2k** [comment]
Zx20 series BIOS does not support NVMe boot directly. So you must have a regular sata HD/SSD installed to host OC. Then you may boot NVME via OC.
