### ISSUE TITLE
install monterey 12.3  (Resolved - with proper patched CpuDef for 2643V2 CPUs)

### ISSUE THREAD

**Issue by liujixu1984** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#2]
你好!
我是z820 
e5 2643 v2 x2
按照您的bios设置，
使用u盘启动安装monterey12.3
启动到图片位置就崩溃停止了
你能帮我排除一下问题吗？ 谢谢！
[http://l.119.fate.ml:7002/1.jpg](url)

**Comment by BillDH2k** [comment]
I would suggest to try the following. Since I don't own 2643 V2 CPU, thus I can't verify it, so my suggestion is based on my own understanding.
试试这个步骤。因为我不拥有这款CPU，无法测试证实是否完全正确，所以只是基于自己的理解。

1. Copy the attached SSDT-1.aml to your EFI ACPI folder. And add it to your OC setup (config.plist):
Root->ACPI->Add

把附带的 SSDT-1.aml 拷贝到 EFI ACPI folder，并加入OpenCore的设置中. 这个文件是从 bilbo的 Z820 Guide 借来的。目的是替代 BIOS 中原始的 CpuPm.

This will replace the BIOS's built-in CpuPM code which a new one (this one is copied from bilbo's Z820 guide).

2. Disable SSDT-CPUPM.aml (since you don't have a proper one yet)
Under "Root->ACPI->Add" section, find entry for "SSDT-CPUPM.aml", and set "Enabled->False"

取消 SSDT-CPUPM.aml (因为暂时还没有正确的CPUPM)。

3. Boot your USB installer.
If everything goes well, you should be able to install macOS. 
尝试从U盘安装 masOS。如果一切顺利，macOS应该可以装上了。

Once macOS is up-and-running, your next step is to create a proper CPUPM file for your CPU in order for CPU Power management to work.  You will need to use ssdtPRGen to create such a file. Follow bilbo's guide (Section IV, Step 29) on how to run ssdtPRGen.

下一步，是生成正确的 SSDT-CPMPU.aml 文件。请参照 [biblo's Z820 Guide](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/?do=findComment&comment=2639434), 第五节，步骤29。通过运行ssdtPRGen 完成。

- Extract ACPI.aml from BIOS (Use "Clover F4" method), place the ACPI.aml on your desktop
- Copy SSDT-1.aml to desktop, and rename it as DSDT.aml, then: 
./ssdtPRGen.sh -mode custom -b Mac-F60DEB81FF30ACF6 -p 'E5-2643 v2' -c 3 -x 1 -cpus 2 -l 24

Please read bilbo's guide for details.

Goodluck!
[SSDT-1.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8448218/SSDT-1.aml.zip)

**Comment by liujixu1984** [comment]
谢谢你的回复  我一会测试一下！

**Comment by BillDH2k** [comment]
I've updated the instruction. You will need to extract ACPI.aml from your BIOS (with 2643V2 CPU installed). 
改动更正了上面的说明，增加了从BIOS中抓取 ACPI.aml 的步骤 （使用 Clover 启动，然后按F4键的方法）。

**Comment by liujixu1984** [comment]
您好！
1，拷贝ssdt-1.aml文件到 acpi文件夹
2，禁用ssdt-cpupm
3，启用ssdt-1
4，从usb启动，还是无法正常安装！ 

附上日志与opencore boot 的acpi设置图！

[http://l.119.fate.ml:7002/log.zip](url)

**Comment by BillDH2k** [comment]
I realized that the version of the ssdt-1.aml from bilbo's guide will not for you. Disable it for now. Also disable SSDT-CPMPU. Try again with just a single CPU installed, see if you can pass the installation. If you still can't, there could well be other issue with your hardware. Try to keep your hardware at the minimum for now.

As I said before, I don't own this CPU. Thus, I could only provide limited help. 

刚刚认识到bilbo 版 ssdt-1.aml 版本不适合你。暂时禁用它。同时禁用 SSDT-CPMPU。只安装一个 CPU 再试一次，看看是否可以通过安装。如果仍然不能，那么很可能您的硬件存在其他问题。暂时将额外的硬件插件拿掉，保持在最低限度。看看能否成功。如果可以，再考虑下一步。


正如我之前所说，我不拥有这个 CPU。因此，我只能提供有限的帮助。

**Comment by liujixu1984** [comment]
谢谢你的指导 我测试一下

**Comment by ZZZ8** [comment]
> 你好! 我是z820 e5 2643 v2 x2 按照您的bios设置， 使用u盘启动安装monterey12.3 启动到图片位置就崩溃停止了 你能帮我排除一下问题吗？ 谢谢！ [http://l.119.fate.ml:7002/1.jpg](url)

The same problem as you。。。

**Comment by ZZZ8** [comment]
My CPU is  E5 2687w v2 X2

**Comment by BillDH2k** [comment]
I would suggest that you post your help in bilbo's forum. You and liujixu1984 both have CPUs that need proper CPUPM files. People in that forum may have these CPUs thus the proper CPUPM files.

You should at least create a Clover loader, to capture your BIOS ACPI's (hit F4 key in picker screen). Then post your results.

**Comment by liujixu1984** [comment]
我已经用clover f4 保存下来该文件  但是不知道要怎么操作

[http://l.119.fate.ml:7002/origin.rar](url)

**Comment by BillDH2k** [comment]
Were you able to install with just one CPU installed?
单CPU设置下，安装成功了吗？还是同样的问题？

**Comment by BillDH2k** [comment]
Please try this SSDT-1.aml.  I created based on SSDT-1-CpuDef, from your Clover ACPI dump. Make sure it is the 1st in Root->ACPI->Add.  Disable SSDT-CPUPM, for now. See if you can install.
[SSDT-1.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8469899/SSDT-1.aml.zip)

试试这个 SSDT-1， 根据你用Clover 抓取的ACPI 文件改成。把它放在ACPI->Add 下第一个位置。同时禁用SSDT-CPUPM。看看能否安装成功。

**Comment by BillDH2k** [comment]
Also try this CPUPM file. Just replace SSDT-CPUPM.aml with this one. Make sure you use the same SSDT-1.aml, sent above. 
 
[ssdt-2643V2.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8470021/ssdt-2643V2.aml.zip)

**Comment by liujixu1984** [comment]
好的 一会试一下

**Comment by liujixu1984** [comment]
单处理器我的电脑都没开机，后面两个文件试过还是一样的问题 我想我要放弃了，

但是还是非常感谢你的帮助！谢谢！

**Comment by BillDH2k** [comment]
May be you should try Big Sur first. Also, what is your video card?
要不试试Big Sur。还有你的显卡是什么型号的？

**Comment by liujixu1984** [comment]
我的显卡是gk107核心的650 我之前试过使用你的几个不同版本启动过10.15   11.2都没有成功

**Comment by BillDH2k** [comment]
GK107 (GTX650) only support up to Big Sur. 不支持Monterey 。我抽空再帮你查一下有关正确的CPUPM。

**Comment by BillDH2k** [comment]
At the moment, the only success I've found (for Catalina 10.15.7) was to use Clover to fix the SSDT CpuDef. See this link [here](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/?do=findComment&comment=2745120). This Clover EFI only works for Catalina right now. You can boot directly from it to install Catalina (Remember to change the serial #, once up and running. You can use Clover Configurator to do that, or manually change the serial # from the config.plist). The direct EFI download is here:  [Z820 EFI Clover Catalina](https://drive.google.com/file/d/1KkBuWTPYmpwB13mpBXO5pnsW-hON4f8p/view?usp=sharing).  

目前网上查到的唯一暂时解决方法 （[链接](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/?do=findComment&comment=2745120)），是使用Clover修复SSDT CpuDef。EFI folder下载链接在此（[Z820 EFI Clover for Catalina](https://drive.google.com/file/d/1KkBuWTPYmpwB13mpBXO5pnsW-hON4f8p/view?usp=sharing)）。这是Clover 版，目前只支持Catalina，可以试试。直接拷贝到USB的EFI区，就可以用了。如果成功，使用时别忘了更改成自己的SYMBIOS序列号。

Also, I will receive a 2643 V1 Xeon CPU (not the same as V2, but had similar booting issue), and I will do some testing myself to see if I can find a solution. 我不久会收到2643 V1 CPU，也会试试。

**Comment by liujixu1984** [comment]
你太厉害了 我已经进入安装界面了 万分感谢

**Comment by BillDH2k** [comment]
You also need this updated VoodooTscSych.kext, for total of 12 cores, 24 thread CPUs. The one in the Clover EFI folder is for 16 cores, 32 threads.  你还需要更新你的 VoodooTscSych.kext，以对应 12 个内核、24 个线程 CPU。 原Clover EFI 文件夹中的那个是 为16 核 32 线程的。

[VoodooTSCSync.kext.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8499287/VoodooTSCSync.kext.zip)

Or, you can modify VoodooTscSych.kext yourself: open info.plist of VoodooTscSych.kext (right mouse click->show package contents to review the file), and change "IOCPUNumber -> 23".

![Screen Shot 2022-04-16 at 1 09 29 AM](https://user-images.githubusercontent.com/89153638/163662557-637f8ce4-ab76-4fc5-9f1b-67eebd1c89e6.png)
.

**Comment by BillDH2k** [comment]
Finally figured out how to fix the booting issues for these CPUs, under OpenCore. I've tested with 2667V2 CPUs. But it should also work for your CPUs, with proper patched CpuDef. You can start with my OC 071 EFI (so you can test OpenCore on your exsiting Catalina installed with Clover, assumming you were already succeeded!). 

You will need this file:
- SSDT-1-2643V2-CpuDef.aml (patched Cpu definition)
[SSDT-1-2643V2-CpuDef.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8508214/SSDT-1-2643V2-CpuDef.aml.zip)

1. Copy both files to your EFI/OC/ACPI folder

2. Add it to config.plist, under Root->ACPI->Add (place it on top of the list).

3. Disable SSDT-CPUPM.aml (You will need to create proper one later)

3. Drop Oem CpuDef table (this is one giving booting issue, thus replace them with our own).
   Root->ACPI->Delete (Copy the entries from the screen shot)
   
![ACPI-2643V2-Screen-1](https://user-images.githubusercontent.com/89153638/163879820-a9bb06d2-4645-4b3a-9f1b-7e250963eb26.png)


4. Copy the EFI to your USB EFI partition. Boot up. Test to see if you can boot to your exsting Catalina install.

5. If successful. Your next step is to create proper CPUPM file for 2643V2.

Please report back if the above works. 

Thanks!

终于弄清楚了如何在 OpenCore 下解决这些 CPU 的启动问题。我已经用 2667V2 CPU 进行了测试。但它也应该适用于你的CPU，只要使用适当的 CpuDef 补丁。以我的 OC 071 EFI 为蓝本，可以直接在你现有 Catalina 测试（假设你已经用Clover安装成功了！）。

需要此文件：
- SSDT-1-2643V2-CpuDef.aml（已修补的 CpuDef 文件）

1. 复制到 EFI/OC/ACPI 文件夹
[SSDT-1-2643V2-CpuDef.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8508213/SSDT-1-2643V2-CpuDef.aml.zip)

2. 添加到 config.plist，在 Root->ACPI->Add 下（放在列表顶部）。

3. 禁用 SSDT-CPUPM.aml（你还未有正确的CPUPM）

3. 删除 Oem CpuDef 列表（原始列表无法启动，因此用补丁替换它）。
   Root->ACPI->Delete（按截屏复制）
   

4. 将 EFI 复制到USB EFI 分区。启动。测试是否可以启动你现有的 Catalina 安装。

5. 如果成功。下一步是为 2643V2 创建正确的 CPUPM 文件。

试试，报告结果。

谢谢！

**Comment by liujixu1984** [comment]
按照您的做法 我已经用你的 oc 071成功启动Catalina

我成功制作了2643的cpupm文件  之前加入的SSDT-1-2643V2-CpuDef.aml，以及删除 Oem CpuDef 列表 需要修改复原吗？

**Comment by BillDH2k** [comment]
1. Copy APIC.aml to desktop
   This APIC.aml is from your Clover F4 dump (under Clover APCI/origin folder)

2. Copy SSDT-1-2667V2-CpuDef.aml to desktop. Rename this file to DSDT.aml

3. Grab a copy of ssdtPRGen tool, from https://github.com/Piker-Alpha/ssdtPRGen.sh
   
   Unzip/Uncompress the download (ssdtPRGen.sh-Beta.zip), it should generate a folder with a name: ssdtPRGen.sh-Beta

   Open a terminal, by right-click on the folder icon -> New Termnial at Folder.
   At the command prompt, type: chmod +x ./ssdtPRGen.sh

4. Create CPUPM file

   Type:  ./ssdtPRGen.sh -mode custom -b Mac-F60DEB81FF30ACF6 -p 'E5-2667 v2' -c 3 -x 1 -cpus 2

   This should create a file ssdt.aml at: ~/Library/ssdtPRGen/ssdt.dsl
   This is your CPUPM file!

5. Copy ssdt.aml file to your desktop and rename it, say, SSDT-2667V2.aml.
   Add this to OC's EFI/OC/ACPI folder.
   Add to config.plist,  Root->ACPI->Add.  Make sure it is after the entry for SSDT-1-2667V2-CpuDef.aml

6. Reboot. 

If everything works, please share your final ssd.aml, so others may benefit. Thanks!
  
1.将APIC.aml复制到桌面
    此 APIC.aml 来自你先前用 Clover F4 抓取的文件（在 Clover APCI/origin 文件夹下）

2. 将 SSDT-1-2667V2-CpuDef.aml 复制到桌面。 将此文件重命名为 DSDT.aml

3. 从 https://github.com/Piker-Alpha/ssdtPRGen.sh 下载 ssdtPRGen 工具
   
    解压下载文件（ssdtPRGen.sh-Beta.zip），应生成一个文件夹，名称为：ssdtPRGen.sh-Beta

    打开一个Terminal，右键点击上文件夹图标 -> “New Termnial at Folder”  
    在命令提示符下，键入：chmod +x ./ssdtPRGen.sh 

4. 创建 CPUPM 文件：

    接上，键入指令：./ssdtPRGen.sh -mode custom -b Mac-F60DEB81FF30ACF6 -p 'E5-2667 v2' -c 3 -x 1 -cpus 2

    结果应该生成一个文件 ssdt.aml，位置：~/Library/ssdtPRGen/ssdt.dsl
    这就是2667V2的 CPUPM 文件！

5. 将 ssdt.aml 文件复制到您的桌面并将其重命名，例如 SSDT-2667V2.aml。
    添加到 OC 的 EFI/OC/ACPI 文件夹。
    添加到 config.plist，Root->ACPI->Add。 使其位于 SSDT-1-2667V2-CpuDef.aml 条目的后面

6. 重启。


如果一切正常，可否分享最后生成的ssdt.aml, 我会放在我的GitHub下，让他人也受益。
谢谢！

Note: this procedure also applies to OC 078 EFI.

**Comment by liujixu1984** [comment]
[http://l.119.fate.ml:7002/SSDT-2643V2.aml](url)

这是我生成的2643v2文件  

另外我用oc7.1升级big sur 11.6.5 可以正常启动

**Comment by BillDH2k** [comment]
Good to hear that it worked for you! Also, thanks for sharing the CPUPM file. I've made changes to it, so it should work fully for Dual CPUs setup.
[SSDT-2643V2-upd.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8513889/SSDT-2643V2-upd.aml.zip)

谢谢分享 CPUPM 文件。 我对它进行了更改，这样更完全适用于你的双 CPU 设置。

**Comment by BillDH2k** [comment]
You also need to verify that your CPU power management is fully working, by running AppleIntelInfo.kext.

[AppleIntelInfo.kext.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8514035/AppleIntelInfo.kext.zip)

Copy the attached AppleIntelInfo.kext to a folder. Open a terminal window at its location. Run the following commands:

*** Change the kext permission (only need to do once):

sudo chown -R root:wheel AppleIntelInfo.kext
sudo chmod -R 755 AppleIntelInfo.kext

*** Load the kext:
sudo kextload AppleIntelInfo.kext

*** Monitor the CPU states/results:
sudo cat /tmp/AppleIntelInfo.dat

*** Do something with your system, like playing a YouTube, etc, then check the results again.

You should see something like below. Post your results here.
![Results-AppleIntelInfo](https://user-images.githubusercontent.com/89153638/164032137-f2fda605-7814-4232-9ebd-9a7480e8c6a0.png)

** When you are done, unload the kext:
sudo kextunload AppleIntelInfo.kext 


将附加的 AppleIntelInfo.kext 复制到一个文件夹中。 在其位置打开一个终端窗口。 运行以下命令：

*** 更改 kext 权限（只需要做一次）：

sudo chown -R root:wheel AppleIntelInfo.kext
sudo chmod -R 755 AppleIntelInfo.kext

*** 加载 kext：

sudo kextload AppleIntelInfo.kext

*** 监控 CPU 状态/结果：

sudo cat /tmp/AppleIntelInfo.dat

*** 让系统运行一会，比如播放 YouTube 等，然后再次检查结果。

你会看到如同下面这样的结果。 把你的结果发上来验证一下。

**Comment by BillDH2k** [comment]
> 按照您的做法 我已经用你的 oc 071成功启动Catalina
> 
> 我成功制作了2643的cpupm文件 之前加入的SSDT-1-2643V2-CpuDef.aml，以及删除 Oem CpuDef 列表 需要修改复原吗？

You must load SSDT-1-2643V2-CpuDef.aml.  Whether "Drop Oem CpuDef" is still needed, you can try without it, since it should be overrided by SSDT-1-2643V2-CpuDef.aml.
 
SSDT-1-2643V2-CpuDef.aml 必须保持。至于是否解除“删除 Oem CpuDef 列表”，你可以试试如果不删除，结果如何。用AppleIntelInfo.kext 验证。

**Comment by BillDH2k** [comment]
Update: I've tested that you must keep "Drop Oem CpuDef" enabled. 

“删除 Oem CpuDef 列表” 必须保留，因为补丁只是替代其中的一部分，剩下的还会干扰，除非单独找出改掉，所以干脆全部删除。

**Comment by liujixu1984** [comment]
按照你的步骤，运行cinebench两个处理器都工作起来了


以下是记录:

;;;AppleIntelInfo.kext v2.9 Copyright © 2012-2017 Pike R. Alpha. All rights reserved.
logIGPU..................................: 0
logCStates...............................: 1
logIPGStyle..............................: 1

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......: 12 (1200 MHz)
Maximum non-Turbo Ratio/Frequency........: 35 (3500 MHz)
Maximum Turbo Ratio/Frequency............: 38 (3800 MHz)
P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU P-States [ 32 (36) 37 ]
CPU C3-Cores [ 1 2 3 ]
CPU C6-Cores [ ]
CPU P-States [ (12) 32 36 37 ]
CPU C3-Cores [ 1 2 3 ]
CPU C6-Cores [ 1 2 4 5 7 ]
CPU P-States [ 12 24 32 (36) 37 ]
CPU C6-Cores [ 0 1 2 4 5 7 8 ]
CPU P-States [ 12 24 31 32 36 (37) ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 2 4 5 6 7 8 10 11 ]
CPU P-States [ (12) 24 25 31 32 36 37 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 10 11 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 10 11 ]
CPU P-States [ (12) 22 24 25 31 32 36 37 ]
CPU P-States [ 12 22 24 25 30 31 32 36 (37) ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ (12) 22 24 25 29 30 31 32 36 37 ]
CPU P-States [ (12) 22 24 25 29 30 31 32 33 36 37 ]
CPU P-States [ 12 22 24 25 29 30 31 32 33 (35) 36 37 ]
CPU P-States [ 12 22 24 25 29 30 31 32 33 35 36 37 (38) ]
CPU P-States [ (12) 22 24 25 28 29 30 31 32 33 35 36 37 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU P-States [ 12 22 24 25 28 29 30 31 32 33 34 35 (36) 37 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU P-States [ (12) 22 24 25 26 28 29 30 31 32 33 34 35 36 37 38 ]

**Comment by BillDH2k** [comment]
In P-States, you should see numbers between 12-22, like the one I showed as an example. Let the machine rest a few seconds, then "sudo cat" again, number of times. If you do see numbers below 22, then the PM is fully working.

在 P-States 中，应该看到 12-22 之间的数字，就像我展示的示例一样。 让机器休息几秒钟，然后再次“sudo cat”，重复几次。 如果确实能看到低于 22 的数字，那么 PM 就是完全工作了。

**Comment by liujixu1984** [comment]
是这样的吗？

AppleIntelInfo.kext v2.9 Copyright © 2012-2017 Pike R. Alpha. All rights reserved.
logIGPU..................................: 0
logCStates...............................: 1
logIPGStyle..............................: 1

CPU Ratio Info:
------------------------------------------
Base Clock Frequency (BLCK)............. : 100 MHz
Maximum Efficiency Ratio/Frequency.......: 12 (1200 MHz)
Maximum non-Turbo Ratio/Frequency........: 35 (3500 MHz)
Maximum Turbo Ratio/Frequency............: 38 (3800 MHz)
P-State ratio * 100 = Frequency in MHz
------------------------------------------
CPU P-States [ (12) 30 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 4 7 9 10 11 ]
CPU P-States [ (12) 27 30 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 4 7 8 9 10 11 ]
CPU P-States [ 12 27 30 32 (36) 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 2 4 5 7 8 9 10 11 ]
CPU P-States [ 12 27 30 32 36 (37) 38 ]
CPU C3-Cores [ 0 1 2 3 ]
CPU C6-Cores [ 0 1 2 3 4 5 7 8 9 10 11 ]
CPU P-States [ (12) 27 29 30 32 36 37 38 ]
CPU P-States [ 12 27 29 30 32 33 (36) 37 38 ]
CPU C3-Cores [ 0 1 2 3 5 ]
CPU C3-Cores [ 0 1 2 3 4 5 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ 12 26 27 29 30 32 33 (35) 36 37 38 ]
CPU P-States [ (12) 18 26 27 29 30 32 33 35 36 37 38 ]
CPU P-States [ 12 18 20 26 27 29 30 32 33 (35) 36 37 38 ]
CPU C6-Cores [ 0 1 2 3 4 5 6 7 8 9 10 11 ]
CPU P-States [ 12 18 20 25 26 27 29 30 32 33 (35) 36 37 38 ]
CPU P-States [ 12 18 20 25 26 27 29 30 31 32 33 35 36 (37) 38 ]
CPU P-States [ (12) 18 20 24 25 26 27 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 18 20 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 18 20 22 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 18 19 20 22 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 16 18 19 20 22 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 16 18 19 20 21 22 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 16 17 18 19 20 21 22 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ (12) 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 35 36 37 38 ]
CPU P-States [ 12 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 (36) 37 38 ]

**Comment by BillDH2k** [comment]
YES!  So congratulation! You have a fully working Hackintosh!

**Comment by liujixu1984** [comment]
十分感谢你的指导！谢谢！

**Comment by BillDH2k** [comment]
You are welcome. Along the way, it helped me to figure how to patch CpuDef for these CPUs. Also thank you for your feedback and sharing the CPUPM file from your setup. I will update my GitHub, so it will cover all CPU models.

不客气。在这过程中，它也让我弄清楚如何修补 这类CPU 的CpuDef。 还要感谢你的反馈和分享你的 CPUPM 文件。我会更新GitHub，把新的补丁发布，这样Z820就可以覆盖全部的CPU了。
