### ISSUE TITLE
can't boot after selecting dmg (High Sierra)

### ISSUE THREAD

**Issue by FluttyPNG** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#21]
hi
i have a xeon e5 1620 v1 and a quandro m2000
so due to Maxwell limitation i only can install high Sierra but when I choose the bigh Sierra dmg it only show a message "please go to panic.apple.com to report this panic"

**Comment by BillDH2k** [comment]
Never tried High Sierra with OpenCore. But you could follow [Bilbo's Z820 guide](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/), which detailed High Sierra setup with Clover.
