### ISSUE TITLE
Help needed i've never booted this efi on my system

### ISSUE THREAD

**Issue by elytraVIII** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#22]
Intel Xeon Cpu E5-2609 0 @ 2.40 ghz 2.40 ghz
Gpu nvidia quadro k2000

**Comment by elytraVIII** [comment]
I am new to hackintoshing I need help doing hackintosh on my pc

**Comment by BillDH2k** [comment]
I suggest that you start with Dortania's OpenCore Install Guide, on how to create an USB installation stick, add the EFI to your USB stick, configure your BIOS to boot from USB.

**Comment by elytraVIII** [comment]
Tried, didn't work

**Comment by BillDH2k** [comment]
Make sure you have the latest BIOS. Check your BIOS setting, by following [bilbo's Z820 guide](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/). Also suggest that you post your problem on a forum, e.g. insanelymac.com, where you can get a help from more users. Describe exactly what "didn't work", with screen shots etc.

**Comment by elytraVIII** [comment]
![Uploading 20230312_083033.jpg…]()

**Comment by elytraVIII** [comment]
Thanks for this awesome efi finally booted
