### ISSUE TITLE
Please have an update for the sonoma

### ISSUE THREAD

**Issue by yaanlpc** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#23]
As the official version of Sonoma has been released, and the official of OC to support Sonoma will also be released Oct, any plan to update the OC configuration to adapt to the new MacOS in terms of HPx20 series?

**Comment by mavethee** [comment]
Just DIY.

https://github.com/mavethee/Hackintosh-OpenCore-EFI-HP-Z420#whats-required-to-make-it-boot

Hackintosh needs some knowledge after all, unless it will gonna keep breaking and what willl you do then? 🤔

**Comment by yaanlpc** [comment]
> Just DIY.
> 
> https://github.com/mavethee/Hackintosh-OpenCore-EFI-HP-Z420#whats-required-to-make-it-boot
> 
> Hackintosh needs some knowledge after all, unless it will gonna keep breaking and what willl you do then? 🤔

Its more than some knowledge, kind of like an engineering.

**Comment by ElytrA8** [comment]
Haha nvm

**Comment by BillDH2k** [comment]
Sonoma support added.
