### ISSUE TITLE
Release 3.3, keyboard and mouse not working

### ISSUE THREAD

**Issue by christianjosias** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#25]
Hi

Tried upgrading from 3.2 to 3.3, it boots fine with 3.3, but keyboard and mouse doesn’t work now.

KR Christian Josiassen

**Comment by BillDH2k** [comment]
Update: Fixed the issue (due to missing ACPI files). Please try again. Thanks!

**Comment by christianjosias** [comment]
Hi

It worked, but then i tried upgrading to Sonoma, but now it just keeps rebooting.

I have a Timemachine backup.

KR Christian Josiassen

**Comment by BillDH2k** [comment]
This EFI does not support Sonoma. You will have to wait until I upload the solution.

**Comment by christianjosias** [comment]
Hi

Okay, can I try Ventura?

I also have an MacBook Pro 14 M3 Max, so it’s not a problem, but I can’t wait to try Sonoma on my HP Z620:).

KR Christian Josiassen

**Comment by BillDH2k** [comment]
No. X79 platform (including HP Zx20) does not support Ventura/Sonoma natively, due to lack of AVX2 CPUs. So root patching is required. Unless absolutely necessary, I recommend to stay with Monterey.
