### ISSUE TITLE
Installing Sonoma with version 3.4, boot looping.

### ISSUE THREAD

**Issue by christianjosias** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#26]
Hi

Tried installing Sonoma with version 3.4, after installing Sonoma 14.3.1 it just keeps boot looping.

KR Christian Josiassen
![IMG_2422](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/72458299/ea974aa9-7743-4dbf-9c45-5ca011e4f6c8)

**Comment by BillDH2k** [comment]
What's is hardware? Video Card? Successful with Monterey before? Also, upload your config.plist.

**Comment by BillDH2k** [comment]
Another suggestion: try to boot from USB for fresh install or update.

**Comment by christianjosias** [comment]
Hi

It's an HP Z620:
CPU: 2697v2
GPU: AMD Radeon Pro wx5100 8gb
RAM: 128gb 1600mhz
Storage: 1tb NVME


KR Christian Josiassen

[EFI.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/14282545/EFI.zip)

**Comment by BillDH2k** [comment]
Where is your booting EFI partition placed? Do you have another drive attached at SATA port to host the OC EFI?

If yes, you must boot from USB to perform Sonoma install.

**Comment by christianjosias** [comment]
Hi

I have my EFI on a USB drive, okay so I need to install Sonoma from the OpenCore bootloader? instead of doing an upgrade from Monterey.


KR Christian Josiassen

**Comment by BillDH2k** [comment]
Do you have Monterey installed previously on your  1TB NVME drive? If yes, how did you boot your Monterey before?

**Comment by christianjosias** [comment]
I booted from the usb drive.

**Comment by BillDH2k** [comment]
OK. You need to boot the Sonoma directly from your USB installer (not from your current Monterey) and then install over your Monterey partition.

**Comment by christianjosias** [comment]
I will try that, is my config.plist configured correctly?

**Comment by BillDH2k** [comment]
I see that you don't have SSDT CPU PM for your CPU (2697 V2). Did you have one used for your Monterey? If yes, copy that one over to this EFI, and add it to config.plist (ACPI->Add section). If not, just continue, but you should create one later once macOS is installed.

BTW, even if your last install failed, your Monterey partition is still there. Just use Sonoma USB Installer and install over the Monterey partition.

**Comment by christianjosias** [comment]
Hi

Sorry for the late reply, I don’t see the boot DMG option from the OpenCore Bootloader, So I can’t update from the usb, do you know what the problem could be?

KR Christian Josiassen

**Comment by BillDH2k** [comment]
Did you mean "boot image" from the USB? Have you created the Sonoma USB installer first, then copy your EFI over to the installer? Follow Dortania guide on how to create an USB Sonoma installer (you need a 32GB usb drive). You can use your M3 MacBook Pro to do that.
