### ISSUE TITLE
is  a dual E5-2698V4 cpu supported?

### ISSUE THREAD

**Issue by ferserone** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#27]
Hi 

I currently have hp z620 , dual  e5-2697 v2 which is a 12 core ivy bridge cpu, i managed to install monterey with your efi :)

My question is if E5-2698V4 which is a 14 core broadwell cpu , will work in a hp z620 to install monterey?

Thanks

**Comment by BillDH2k** [comment]
Not on Z620. You need Z440/640/840.

**Comment by ferserone** [comment]
what about  E5-2690 v4 ?

**Comment by BillDH2k** [comment]
No. X79 platform, like these Zx20 series, only support V1/V2 Xeons. V3/V4 Xeons have physically different sockets.

**Comment by ferserone** [comment]
I see, thanks..i will try to get my hands on a HP z840 and try it there too.
