### ISSUE TITLE
Quadro K6000 not able to patch with opencore Legacy patcher

### ISSUE THREAD

**Issue by ferserone** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#28]
Hi,

I have a Quadro K6000 GPU in my hpz620, i would like to have it detected by Monterey

I have tried with opencore legacy patcher, but i got the following:
![5eddcfae-8c34-4700-a3af-de51c5673637](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/160362852/6e69959d-930a-469c-a9e0-2c43d650e6b6)

SIP is disabled, but no effect.

What could be the issue here?

Many thanks!

**Comment by ferserone** [comment]
Additionally i changed in opencore configurator the setting in section NVRAM, variable csr-active-config to have value 02080000

Next to this, i cleared nvram in Recoverymode with command nvram -c ( Bootup USB installer and open terminal) 

After a reboot, the system came up and i was able to install it:
![5fd4aef2-277a-41ae-bec1-04a34500bbaa-root patcher](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/160362852/0c2da89d-f9cb-4cb5-b625-27ef6938c74f)



Then, a reboot was required to apply changes

when the system came back up Monterey detected my GPU..yaaay

![08141b75-41d6-40eb-bb57-ad3f6a0b926f-overvieqw](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/160362852/794762b2-3c1e-4a80-b535-4a8e5382af19)

**Comment by BillDH2k** [comment]
Yes, csr-active-config needs to be set <0308000> (section 7, step 4 if you follow my instruction. BTW: the latest EFI also works on Monterey + OCLP). 

To perform NVRAM reset, at OC picker (OpenCore boot screen). Hit SPACE BAR, to review all boot options, the last one is NVRAM RESET. No need to boot into recovery.

I've changed the config settings, so OC Auxiliary options will be shown by default.

**Comment by ferserone** [comment]
Is there a way to get the GPU recognized without user interaction? Like for instance, i had to do manual steps to get my K6000 recognized by altering settings and using OCLP. 

For user experience, would be great if the detection happens after installation. Is this something easy to implement?

**Comment by BillDH2k** [comment]
Monterey (or newe macOS) does not support nVidia Kepler GPU (K6000). Thus you need OCLP which injects old driver back. You must disable/lower system security settings, via csr-active-config, in order to do that. So no way to get around that. 

It's a simple config.plist edit, then NVRAM RESET (at OC boot screen), to make the new setting active. Again, no need to boot into Recovery mode.

**Comment by ferserone** [comment]
I have seen that, the nvram reset at oc boot screen, thanks..its a bit better this way. I was just wondering if it could be automated, but its not a big deal. I just need to make sure i write it down in my step-by-step manual. Thanks!
