### ISSUE TITLE
HP Z620 slow performance

### ISSUE THREAD

**Issue by christianjosias** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#29]
Hi

Why is my Geekbench 6 score so low?

KR Christian Josiassen
![Skærmbillede 2024-03-27 kl  20 47 43](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/72458299/60f390f2-bdd4-4563-99f8-d73df8925e68)

**Comment by BillDH2k** [comment]
Have you created the custom SSDT CPU PM for your CPU (2697v2)? Without it, the CPU will not run at high clock speed. Check section "6. Pre/Post Install".

Basically, you need to create an ACPI BIOS dump (using Debug version of OpenCore, with "SyReport" option enabled), and run ssdtPRGen tool. If you can't figure out, send me the ACPI dump (two of the files from the dump).

If possible, try to ask for help here: [[Guide] Hackintosh HP Z420/Z620/Z820 OpenCore Sonoma/Ventura/Monterey](https://www.insanelymac.com/forum/topic/358714-guide-hackintosh-hp-z420z620z820-opencore-sonomaventuramonterey/)

**Comment by christianjosias** [comment]
Hi


Sorry for the late answer, you are right I don't have an SSDT for my 2697v2. I have uploaded the ACPI Dump.


KR Christian Josiassen
[ACPI.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/14813251/ACPI.zip)

**Comment by BillDH2k** [comment]
Try this: 
[SDDT-2697V2.aml.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/14813720/SDDT-2697V2.aml.zip)

Make sure you use the "config-IvyCPU.list" template. Add it to "config.plist->Root->ACPI->Add" section.

**Comment by christianjosias** [comment]
It works!

Thank you so much.

![Skærmbillede 2024-03-31 kl  09 28 08](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/72458299/a1e56d87-4cd4-4816-923e-e6be6d1e0e79)

KR Christian Josiassen
