### ISSUE TITLE
PCIe NVME SSD not recognized as bootable drive [solved]

### ISSUE THREAD

**Issue by lisavani** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#3]
Hello Bill,

hopefully you can and will help me with the following problem. I have been working for days on my HP Z420 with your opencore 2.1. Big Sur works fine on a SATA SSD but my PCIe NVME SSD in slot 4 is not seen.
I am wondering what I am doing wrong. I don't see any clues in your config.

My current configuration is HP Z420, Bios v. 3.96, E5-2697 v2, nVidia Quadro K4000, Big Sur 11.6.5

Sincerely,

Lisa

**Comment by BillDH2k** [comment]
If you boot from the USB with my EFI, you should see NVME disk, unless you have an incompatible disk. For OC to see the NVME disk during booting, you must add/enable NvmExpressDxe.efi to: UEFI->Drivers. For macOS to access it properly, you need add/enable NVMeFix.kext to Kernel->Add.   My EFI folder have both. So, if you can't see the NVME dick, check for compatibility (or test it under Windows).

Also, Z420 BIOS can't boot directly from NVME. You must have a Sata drive installed to install/host OC EFI.

**Comment by lisavani** [comment]
Thanks for the quick reply. I notice that I have not been careful enough in my question.
My HP Z420 boots from OC 075 in the EFI from a sata ssd. Besides that I have the PCIe NVME ssd and it is usable for reading and writing, but it does not get presented as bootable drive while booting from my OS 075. That doesn't happen either when I boot from your OC EFI folder on an USB drive.
I have a Samsung NVME 980 on an Angelbird Wings PX1 pcie adapter card and it obviously has a working bootable OSX on it, which works well on a real Mac Pro.

Could it be that a Z420 can only boot from an HP Turbo NVME drive?
What combination(s) are you having success with?

Sincerely,

Lisa

PS I have changed the title of this issue so that it is clearer what this is about.

**Comment by BillDH2k** [comment]
When you boot Big Bur from your Sata OC, were you able to see all the partitions in the Samsung drive, using Disk Utility? If the answer is yes, then in theory you should be able to install & boot from there (via the OC installed on the Sata drive). If you can't do that, then the issue could be likely related to the way the "real OSX" was installed. I am not an expert here, but if you reformat your Samsung and start fresh you should be able to boot from there (Make sure you backup your data first!, if you want to try that).

I had success with 500GB NVME drives (one Western Digital, one Crucial), using cheap PCI-E adapters ($10 from eBay). But I must use a regular Sata drive to host the OC loader. The Big Sur was installed on the NVMe disk, but the EFI folder was in Sata drive (EFI Partition).

**Comment by lisavani** [comment]
Hello again. After much reading and expirimenting I have found the cause. The PCIe NVME was not seen as bootable because this was prevented by the IntelE1000.kext. I set this to false and set the Intelmausii.kext, which was already present, to true. Since then, the NVME is bootable!
It seems that using the IntelE1000 kext is not good in an HP Z420.

Thanks again for your thoughts and your configuration of course, which is otherwise very useful as a guide.

Kind regards,

Lisa

**Comment by BillDH2k** [comment]
Thank you for your feedback!! Another post is also reporting booting issue with IntelE1000.kext, for Z420. I was never experienced this issue, since my NvMe drive way installed on Z620/Z820, but not Z420! I shall make the IntelMausi.kext as the default. Thanks again.
