### ISSUE TITLE
Kernel panic when updating from Big Sur (11.7.10) to Monterey (12.7.5) with latest release on Ivy Bridge z620 

### ISSUE THREAD

**Issue by bennals** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#30]
Thanks for your work on keeping these good old machines alive!

I just tried updating a z620 (dual 2680 v2) using the latest release (3.4) and found that the installer would kernel panic with the following error straight after the first restart (once the update installer had finished the prep work for the update).

`Refusing new kext com.apple.driver.AppleIntelCPUPowerManagement, V222.0: a prelinked copy with a different executable UUID is already present.`

I notice that the Kext folder has the AppleIntelCPUPowerManagement and AppleIntelCPUPowerManagementclient kexts in it, whereas the previous releases didn't.  I'm guessing that means that those kexts are only relevant to Ventura/Sonoma and should be removed/disabled for Big Sur or Monterey installations?

I didn't read anything about that in the readme (sorry if I've missed it), but if that is the case, and Big Sur/Monterey installers should only use the 3.3 release, perhaps it's worth making that clear somewhere?

I just finished a smooth installation using the 3.2 release (thanks!) and I suspect the 3.3 would have been the same.

Cheers,

Bill.

**Comment by BillDH2k** [comment]
Will check the config. Thanks!

**Comment by BillDH2k** [comment]
@bennals Just rechecked the latest EFI. AppleIntelCPUPowerManagement, V222.0, should not load unless the OS is Ventura (22.x.x) or higher. Here is the kernel patch section (see last two lines):

![image](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/assets/89153638/e16fbd08-87bd-40d1-bbd4-963794455342)

So I am kind of puzzled why you encountered the error.

Follow up: Could you explain the sequence of your Monterey upgrade process? From within the OS (Big Sur), or, from an USB installer (boot/install over Big Sur partition)?

**Comment by bennals** [comment]
Yes, it was from within the OS (Big Sur), and I downloaded the updater from the App Store.

**Comment by BillDH2k** [comment]
I did a test on my backup setup. Using the latest EFI (V3.4.1), I was able to update successfully from Big Sur 11.7.9 to Monterey 12.7.5. Update was launched within Big Sur, from the Monterey update package downloaded from mac App Store. My setup, however, is a single 2667V2 Z620. But I don't believe it would make a difference for Dual CPUs (Note: dual CPU configuration also worked as expected).

So not sure what happened to your setup.

**Comment by bennals** [comment]
Fair enough, thanks for looking into it.  I had only just updated Big Sur from 11.6.5 to 11.7.10 the day before attempting the update to Monterey, so I guess that's a possible difference in our setups.

Anyway, the presence of this issue might be enough for someone who encounters the same thing to prompt them to just try the previous release.  Perhaps you could put a note somewhere on the same page that one user reported an issue?

**Comment by BillDH2k** [comment]
@bennals  I will make a recommendation to use earlier EFI if no Ventura/Sonoma is used. Thanks for testing it.
