### ISSUE TITLE
Unable to start after changing config file（1.0）

### ISSUE THREAD

**Issue by UDPN-zhangXueFeng** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#5]
OC：Driver at 0 cannet be loaded - unsupported（stuck here）
configure：e5 2667 v1

**Comment by BillDH2k** [comment]
You need to be more specific. What changes did you make to config file? Was it working before you made changes?

> OC：Driver at 0 cannet be loaded - unsupported
This is normally a harmless message. There was an entry under Root->DeviceProperties->Add, which you can simply delete.

（stuck here）

**Comment by BillDH2k** [comment]
Another follow up, if this helps:  Since you are using V1 xeon, you must use my OC 071 EFI. Any OC version higher than 0.7.1 will not able to boot V1 Xeon (Sandy Bridge) on this HP machine (apply to Z420/Z620/Z820).

**Comment by UDPN-zhangXueFeng** [comment]
Because my graphics card is 5500xt, I added agdpmod=pikera, and then efi can't be used (OC: Driver at 0 cannet be loaded - unsupported (stuck here)), it was normal before the change

**Comment by UDPN-zhangXueFeng** [comment]
First of all, thank you for the efi you provided. I am also using the version of 071. Similarly, it is not only the parameter (agdpmod=pikera), but I also change other parameters, such as random generation of three codes, which cannot be activated.
