### ISSUE TITLE
Radeon 560X no HA (Solved - iMacPro1,1 SYMBIOS support with updated USBInjectAll.kext)

### ISSUE THREAD

**Issue by aferrara814** [BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore#8]
Hi, I have installed Monterey 12.3 with your EFI, thank you.

Now I can't get the hardware acceleration on my Radeon 560X. You can help me?
And help me to insert the correct cpu type into opencore?
Now the system read that: 2 x 1,8 GHz Intel Xeon E5 12 core

![Z620](https://user-images.githubusercontent.com/83160600/167083725-c6eedd4e-6c51-4302-b19c-5be67d615d15.jpg)
![Schermata 2022-05-06 alle 12 41 36](https://user-images.githubusercontent.com/83160600/167117611-bfe1127e-87e5-46e9-8dca-8e5d7bc1ee59.png)

**Comment by aferrara814** [comment]
Latest testing.
I have do the usb pendrive with monterey 12.3 with your EFI folder but not boot.


I the readme file you have write that:
Pre-Install: You must add your own Serial # & Board Info. I have removed the anonymous # for safety reason.

I can boot without insert the serial and board info?
I don't know where to get it and how to put it in the EFI folder, you can help me please?

**Comment by aferrara814** [comment]
Oh my God, I have not enabled the Legacy ACPI Tables.
Now I have enabled it and seems boot on Monterey 12.3

**Comment by BillDH2k** [comment]
Your video is "Metal" supported already.  As for other "features", you would need to ask for help in other hackintosh forum. I am not an expert here, and I don't own your video card.

You don't need to specify any CPUID/type. But you should generate CPUPM files for your CPU, for optimal power management. Refer to bilbo's guide [here](https://www.insanelymac.com/forum/topic/335860-guide-2018-z820-high-sierra-the-great-guide-sucess/), Step #29. Even though, the guide was written for High Sierra, but Step #29 also applies for newer macOS. You need generate ACPI dump from your system, like using Clover loader with F4 key method. Just follow the guide.

**Comment by aferrara814** [comment]
I think you can help me because to get the graphics acceleration I just need to set iMac Pro 1,1 in the SMBIOS.


Except that if I set iMac Pro 1,1 in the SMBIOS I lose all the usb ports. I cannot use mouse and keyboard on any usb port on my z620. Can you help me? Can you tell me how to setup iMac Pro 1.1 in SMBIOS by making usb ports work?

**Comment by BillDH2k** [comment]
I see. Try this updated USBInjectAll.kext
[USBInjectAll.kext.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8653429/USBInjectAll.kext.zip)

**Comment by aferrara814** [comment]
I have to install it before set the SMBIOS? When I chose the right SMBIOS I have to check the "add this section in config.plist" on not check/select this box?

How I install this kext? Simply replace into EFI partition or I have to install it via opencore configurator?

**Comment by BillDH2k** [comment]
1. Replace the existing USBInjectAll.kext (in EFI/OC/Kext/ folder) with this updated file.
2. Change SUMBIOS to "iMacPro1,1" (config.plist->Root->PlatformInfo->Generic->SystemProductName). I use Proper-Tree to edit this file.
3. You would also need to provide new set of SystemSerialNumber and SystemUUID to match iMacPro1,1 (like using GenSYMBIOS tool)

**Comment by aferrara814** [comment]
Tryed but no one usb port work.
Here is my new config.plist with iMacPro 1,1 with SystemSerialNumber and SystemUUID to match iMacPro1,1.

Help me please to do the work that!!
[config.plist.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8658908/config.plist.zip)

**Comment by BillDH2k** [comment]
Try this version of USBInjectAll.kext. I've tested and it worked on my setup.
[USBInjectAll.kext.zip](https://github.com/BillDH2k/Hackintosh-HP-Z420-Z620-Z820-OpenCore/files/8666200/USBInjectAll.kext.zip)

**Comment by aferrara814** [comment]
Yeeees my friend, works perfectly and now I have qe/ci enabled and working on my Radeon RX 560.

You can get the usb3 working?

On my z620 still working only usb2.0

Your ethernet is working?

**Comment by aferrara814** [comment]
When I connect the ethernet cable into RJ45 port the system recognize it as connected, but after 2 second the system brick and I have to restart with reset button.

Same on ethernet port and on AMT port.

Same results if I connect ethernet cable and reboot pc. It still brick on login

**Comment by BillDH2k** [comment]
Built-in USB3 will not work. You should consider buying USB3 PCIe add-on card. Like the one made by Inateck, on eBay.

As for the ethernet, try "AppleIntelE1000e.kext", instead of "IntelMausi.kext". Both files are in the OC/Kexts folder.

**Comment by aferrara814** [comment]
I have both kext into OC/kext folder. I try removing IntelMausi.kext and rebooting?
Simple remove it from OC/kext folder

**Comment by BillDH2k** [comment]
You need to modify config.plist to "enable" or "disable" which kext driver to load. No need to delete any files. If you haven't done so, learn how to use "Propertree" editor to edit config.plist. The relevant section is: "config.plist->Root->Kernel->Add".
For  each of the listed kext's, you can set "Enable" to "True" or "False" to activate or disable it.

**Comment by aferrara814** [comment]
Yees, it works perfectly with only AppleIntelE1000e.kext.

Now, the last question, is important to set the correct CPUID/type for optimal power management?
So if I don't configure/insert it is a big problem?

**Comment by BillDH2k** [comment]
No. Not for this platform.

**Comment by aferrara814** [comment]
Many many thanks many. Best support! Thank you so much
